### ISSUE TITLE
Dependencia que no existe

### ISSUE THREAD

**Issue by sergiodxa** [miuel/shot-share#1]
https://github.com/miuel/shot-share/blob/master/shsh-api/users.js#L5
La dependencia que importas en esa línea no existe. Cuando importas/requeris una dependencia si no colocas `./` o similar para indicar el path donde se encuentra esa dependencia Node.js va a buscarla siempre en la carpeta **node_modules**, dado que nunca la instalas usando npm (y que no existe en npm) nunca la va a encontrar.

**Comment by miuel** [comment]
@sergiodxa si, pero en este caso shsh-db actua como una dependencia de node, o no?. De todas formas agregue el ./ como una ruta(const Db = require('./shsh-db')), pase el test y me fallo por eso:

module.js:457
    throw err;
    ^

Error: Cannot find module './shsh-db'

**Creo que esta bien como estaba antes, la carpeta shsh-db esta en node_modules**

**Comment by sergiodxa** [comment]
No hagas eso, usa `node_modules` para las dependencias que instales de npm, nunca subas algo propio a `node_modules`, esa carpeta siempre se ignore en Github por lo que si alguien se baja este repo le va a fallar ya que `shsh-db` nunca si instala mediante npm y por lo tanto no esta en `node_modules.`

**Comment by miuel** [comment]
Lo hace de forma automatica. Cuando se requieren los modulos como dependencia se utiliza un linkeo que lo instala en tu node_modules como una dependencia mas de npm, Luego tambien hay que dejar constancia en el package.json de ello...
