### ISSUE TITLE
¿Para que usas Babel?

### ISSUE THREAD

**Issue by sergiodxa** [miuel/shot-share#2]
https://github.com/miuel/shot-share/blob/master/shsh-api/package.json
Según tu package.json estas descargando babel-runtime, un preset y dos plugins. Para que? Si usas Node.js v6 y Micro v6 no necesitas ninguna de esas dependencias ya que Node ya soporta ES6 (excepto módulos) y Micro internamente usa una librería para soportar Async/Await

**Comment by miuel** [comment]
Babel se usa para luego pasar el linter, el resto de plugins no recuerdo ahora porque se han requerido. Lo cierto es que he seguido las clases y claro, creo que julian utilizo unas versiones antiguas tanto de node como micro, por eso talvez necesitaba babel, yo ahora con versiones 6 no sabia que no las necesitaba.
