### ISSUE TITLE
Invalid body

### ISSUE THREAD

**Issue by sergiodxa** [miuel/shot-share#3]
Ya que el error que te da es invalid body, verifica que respuesta te devuelve el cliente de la base de datos, es posible que te este devolviendo algo mal ahí y por eso al mandarlo por micro te da invalid body.

**Comment by miuel** [comment]
Estuve revisando el código en **shsh-db**, tenia vario tips, los he corregido los he dejado como en la version original de Julian. Al pasar los test me da error en authenticate user _(pego un pantallazo debajo del error)_. Lo raro es que al volver a hacer **npm test** los test pasan bien ya, porque es esto ?. Sera que falla la primera vez que se hace la verificación ?. Puede que el error sea esto ?. Sabrias decirme que pasa para solucionarlo ?
El modulo **shsh-client** lo he revisado todo y me pasan bien los test creo que ese esta bien.
Estoy volviendo a revisar **shsh-api** tanto los ficheros como los videos y el código que ha dejado Julian nuevamente, lo que me llevara un rato mas...
1. db-test › authenticate user
   failed with "Cannot perform write: primary replica for shard ["", +inf) not available in:
   r.db("shshDb_7bAnSteikiPMOi6m0oCOEr").table("users").insert({"name": "A random user", "username": "user_3DdPmy5Epy8YAwew2nT3qp", "password": "902d68b18dc77aacea978b0c06762ae4e8d9c86d5a959ea7642ad08f7f252918", "email": "6iBcK5hLRLh4qVxVo57zgp@shsh.test", "createdAt": r.ISO8601("2016-09-21T12:22:46.374Z")})
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       ReqlOpFailedError.ReqlError [as constructor](/Users/maikol/Platzi/FrontEnd/Curso_Definitivo_JavaScript/shsh-db/node_modules/rethinkdb/errors.js:23:13)
       ReqlOpFailedError.ReqlRuntimeError [as constructor](/Users/maikol/Platzi/FrontEnd/Curso_Definitivo_JavaScript/shsh-db/node_modules/rethinkdb/errors.js:90:51)
       ReqlOpFailedError.ReqlAvailabilityError [as constructor](/Users/maikol/Platzi/FrontEnd/Curso_Definitivo_JavaScript/shsh-db/node_modules/rethinkdb/errors.js:167:56)
       new ReqlOpFailedError (/Users/maikol/Platzi/FrontEnd/Curso_Definitivo_JavaScript/shsh-db/node_modules/rethinkdb/errors.js:178:52)
       mkErr (/Users/maikol/Platzi/FrontEnd/Curso_Definitivo_JavaScript/shsh-db/node_modules/rethinkdb/util.js:177:10)
       TcpConnection.Connection._processResponse (/Users/maikol/Platzi/FrontEnd/Curso_Definitivo_JavaScript/shsh-db/node_modules/rethinkdb/net.js:152:16)
       TcpConnection.Connection._data (/Users/maikol/Platzi/FrontEnd/Curso_Definitivo_JavaScript/shsh-db/node_modules/rethinkdb/net.js:122:12)
       Socket.<anonymous> (/Users/maikol/Platzi/FrontEnd/Curso_Definitivo_JavaScript/shsh-db/node_modules/rethinkdb/net.js:683:32)
       readableAddChunk (_stream_readable.js:176:18)
       Socket.Readable.push (_stream_readable.js:134:10)
       TCP.onread (net.js:543:20)
   From previous event:
       Db.saveUser (/Users/maikol/Platzi/FrontEnd/Curso_Definitivo_JavaScript/shsh-db/lib/db.js:250:20)
       _callee9$ (db-test.js:124:12)
       tryCatch (/Users/maikol/Platzi/FrontEnd/Curso_Definitivo_JavaScript/shsh-db/node_modules/regenerator-runtime/runtime.js:62:40)
       GeneratorFunctionPrototype.invoke [as _invoke](/Users/maikol/Platzi/FrontEnd/Curso_Definitivo_JavaScript/shsh-db/node_modules/regenerator-runtime/runtime.js:336:22)
       GeneratorFunctionPrototype.prototype.(anonymous function) [as next](/Users/maikol/Platzi/FrontEnd/Curso_Definitivo_JavaScript/shsh-db/node_modules/regenerator-runtime/runtime.js:95:21)
       Test.fn (db-test.js:117:1)
   From previous event:
       _combinedTickCallback (internal/process/next_tick.js:67:7)
       process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by sergiodxa** [comment]
Ni idea, parece ser un error de RethinkDB y no se como funciona esta DB, si decis que el error ocurre solo la primera vez que corren los test puede ser que falta un dato en la DB y por eso falla. Capaz @julianduque pueda ayudarte más con este error de RethinkDB.

**Comment by miuel** [comment]
Buenas @julianduque no soy capaz de avanzar con esto, si lees los comentarios, veras que he revisado todos los modulos, he mirado nuevamente los videos, y sigo sin poder solucionar el problema de invalid body al momento de crear un usuario...

**Comment by miuel** [comment]
@julianduque. Mirando rethinkdb después de los test cuando hago un consulta y del error "invalid body" , en Data Explore consulte la table 'users' con la siguiente query:
`r.db('shshdb').table('users')` lo que me arroja no resultado (No results returned...), sin embargo si reviso en la pestaña de Tables veo que si existen varias tables 'users' e 'images' . Aunque no tengan datos dentro.
Luego si intento consultar con la query:
`r.db('shshdb').table('users').info()` si me aparece información. 

Adjunto pantallazos de lo comentado.

Todo esto que esta bien ?, me parece raro que se genere la table users y luego no me deje guardar un usuario ... ?

![screen shot 2016-09-21 at 22 02 14](https://cloud.githubusercontent.com/assets/18704457/18729315/3e3863c4-8049-11e6-8c6f-acf63fee004f.png)
![screen shot 2016-09-21 at 22 02 48](https://cloud.githubusercontent.com/assets/18704457/18729316/3e40e990-8049-11e6-8e89-8836f35a5897.png)
![screen shot 2016-09-21 at 22 03 07](https://cloud.githubusercontent.com/assets/18704457/18729317/3e42c5d0-8049-11e6-8d8a-3545f41bd783.png)
![screen shot 2016-09-21 at 22 12 11](https://cloud.githubusercontent.com/assets/18704457/18729318/3e42eba0-8049-11e6-9420-aa262ce0bb67.png)

**Comment by miuel** [comment]
@julianduque si lees estos comentarios, comentarte que los test de la base de datos ya fuinconan bien .

**Comment by julianduque** [comment]
@miuel hola, apenas veo los comentarios, las bases de datos que veias son las de pruebas que por alguna razón no se estaban eliminando.

Todavía sigue ocurriendo el error?

**Comment by miuel** [comment]
Ah vale @julianduque no pasa nada. Mejor hablemos por aqui, que nose como va Slack aún soy nuevo en esa plataforma... Los test de la BBDD ya corren bien, sin problemas, pero **si** tengo aún el error 500: invalid body al intentar hacer signup...
